git_email: github@allenofmn.com

homebrew_installed_packages:
  - terraform
  - postgresql

homebrew_taps:
  - homebrew/core
  - homebrew/cask
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - brave-browser
  - docker
  - iterm2
  - sublime-text
  - balenaetcher
  - discord
  - slack
  - zoom
  - spotify
  - steam
  - flux
  - cyberduck

install_inconsolata: true
install_rvm: true
install_oh_my_zsh: true

configure_dotfiles: true
dotfiles_repo: git@github.com:carlallen/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .zshrc
  - .osx
  - .gemrc

configure_osx: true
osx_script: "~/.osx --no-restart"

configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "AdvancedNewFile"
  - "Ansible"
  - "Dockerfile Syntax Highlighting"
  - "Git"
  - "GitGutter"
  - "HTML Mustache"
  - "Jinja2"
  - "Package Control"
  - "Rails Completions"
  - "Sass"
  - "Splunk Conf File Syntax Highlighting"
  - "Terraform"
  - "Theme - Phoenix"
  - "Theme - Soda"
