homebrew_installed_packages:
  - terraform
  - postgresql

homebrew_taps:
  - homebrew/core
  - homebrew/cask
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - brave-browser
  - iterm2
  - sublime-text
  - discord
  - steam
  - slack
  - spotify
  - flux
  - cyberduck
  - docker

install_inconsolata: true
install_rvm: true
install_oh_my_zsh: true


# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text 3'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "AdvancedNewFile"
  - "Ansible"
  - "Dockerfile Syntax Highlighting"
  - "Git"
  - "GitGutter"
  - "HTML Mustache"
  - "Package Control"
  - "Rails Completions"
  - "Sass"
  - "Splunk Conf File Syntax Highlighting"
  - "Terraform"
  - "Theme - Phoenix"
  - "Theme - Soda"
