---
- name: Ansible Mac
  hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.dock

  tasks:
    - name: Import Gitconfig
      ansible.builtin.import_tasks: "tasks/gitconfig.yml"
      tags: ['gitconfig']

    - name: Import Programming Fonts
      ansible.builtin.import_tasks: tasks/programming_fonts.yml
      when: install_programming_fonts
      tags: ['programming_fonts']

    - name: Import RVM
      ansible.builtin.import_tasks: tasks/rvm.yml
      when: install_rvm
      tags: ['rvm']

    - name: Import oh-my-zsh
      ansible.builtin.import_tasks: tasks/oh-my-zsh.yml
      when: install_oh_my_zsh
      tags: ['oh-my-zsh']

    - name: Import Sublime Text
      ansible.builtin.import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']

    - name: Import OSX
      ansible.builtin.import_tasks: tasks/osx.yml
      when: configure_osx

    - name: Import Luminia Installer
      ansible.builtin.import_tasks: tasks/lumina_installer.yml
      when: install_lumina
