- name: Check if Lumina is installed
  stat:
    path: "/Applications/Lumina.app"
  register: lumina_installed

- name: Download the Lumina app
  ansible.builtin.unarchive:
    src: https://dist.getlumina.com/beta/Lumina-0.2.5-8-mac-m1.zip
    dest: "~/Desktop"
    mode: "755"
    remote_src: yes
  when: not lumina_installed.stat.exists

- name: "Convert Lumina to skip EULA"
  raw: "hdiutil convert -quiet ~/Desktop/Lumina-0.2.5-8-mac-m1.dmg -format UDTO -o ~/Desktop/Lumina.cdr"
  when: not lumina_installed.stat.exists

- name: "Mount Installer"
  raw: "hdiutil attach -quiet -nobrowse -noverify -noautoopen -mountpoint ~/Desktop/LuminaInstaller ~/Desktop/Lumina.cdr"
  when: not lumina_installed.stat.exists

- name: "Move Lumina to Applications"
  raw: "mv ~/Desktop/LuminaInstaller/Lumina.app /Applications/"
  when: not lumina_installed.stat.exists

- name: "Detach Lumina Installer"
  raw: "hdiutil detach ~/Desktop/LuminaInstaller/"
  when: not lumina_installed.stat.exists

- name: Remove lumina installer folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/Desktop/__MACOSX
    - ~/Desktop/Lumina.cdr
    - ~/Desktop/Lumina-0.2.5-8-mac-m1.dmg
  when: not lumina_installed.stat.exists
