- name: Detect rvm binary
  ansible.builtin.stat:
    path: ~/.rvm/bin/rvm
  register: rvm_binary

- name: Install rvm
  ansible.builtin.shell:
    cmd: set -o pipefail && curl -sSL https://get.rvm.io | bash -s stable
    executable: /bin/bash
  changed_when: not rvm_binary.stat.exists
