---
- name: Ensure Sublime Text directories exist.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ sublime_base_path }}/Packages"
    - "{{ sublime_base_path }}/{{ sublime_config_path }}"
    - "{{ sublime_base_path }}/Installed Packages"

- name: Ensure Sublime Package Control is installed.
  ansible.builtin.get_url:
    url: "https://packagecontrol.io/Package%20Control.sublime-package"
    dest: "{{ sublime_base_path }}/Installed Packages/Package Control.sublime-package"

- name: Ensure Sublime Package Control Packages are configured.
  ansible.builtin.template:
    src: templates/Package_Control.sublime-settings.j2
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/Package Control.sublime-settings"

# - name: Ensure Sublime freeze_ruby_files is installed
#   copy:
#     src: files/sublime/freeze_ruby_files/
#     dest: "{{ sublime_base_path }}/Packages/freeze_ruby_files/"

- name: Ensure Sublime text user Preferences and theme are set.
  ansible.builtin.copy:
    src: "files/sublime/{{ item }}"
    dest: "{{ sublime_base_path }}/{{ sublime_config_path }}/{{ item }}"
  loop:
    - "Default (OSX).sublime-keymap"
    - "GitHub.tmTheme"
    - "Mac Classic.tmTheme"
    - "Preferences.sublime-settings"
